### ISSUE TITLE
Golang version requirement

### ISSUE THREAD

**Issue by lemire** [robskie/bp128#1]
I could be wrong/confused, but I had to upgrade to Go 1.5.1.

Note: you might enjoy this C project... seems closely related... https://github.com/lemire/simdcomp

**Comment by lemire** [comment]
Moreover, on a haswell processor, here are my results...

```
$ go run benchmark.go
BenchmarkPack32          	 1018 mis
BenchmarkUnPack32        	 2585 mis
BenchmarkDeltaPack32     	 1621 mis
BenchmarkDeltaUnPack32   	 4234 mis
BenchmarkPack64          	  581 mis
BenchmarkUnPack64        	  907 mis
BenchmarkDeltaPack64     	  670 mis
BenchmarkDeltaUnPack64   	 1105 mis
````

This is quite different from the numbers you report, but that's not surprising if you are relying on a Sandy Bridge (2011) laptop processor.

I am concerned about your benchmarking methodology. Let us look at this code...

https://github.com/robskie/bp128/blob/master/benchmark/benchmark.go#L140-L147


You are loading data, much of it not in cache maybe, and pushing it to buffers that may not fit in cache.  There are streaming instructions for such purposes (e.g., movntdq) but one typically wants to decompress to cache.

If you are not decompressing to cache, you risk hitting performance limits that are somewhat artificial.

**Comment by robskie** [comment]
> I could be wrong/confused, but I had to upgrade to Go 1.5.1.

It uses the encoding package, so I think it requires Go 1.3 and up.

> Note: you might enjoy this C project... seems closely related... https://github.com/lemire/simdcomp

Yeah, I've seen that. I actually based my code on that and on the C++ implementation, but it currently doesn't support 64-bit integers.

> You are loading data, much of it not in cache maybe, and pushing it to buffers that may not fit in cache. There are streaming instructions for such purposes (e.g., movntdq) but one typically wants to decompress to cache.

Thank you for pointing that out. I'm currently thinking of a better way to benchmark it.

**Comment by lemire** [comment]
@robskie 

When working with 64-bit integers that would fit in 32 bits, it might be advantageous to use the 32-bit code and the just upsample the vectors. This could lead to faster processing.

**Comment by robskie** [comment]
Unfortunately, I'll be using this to encode integers up to 16 digits long.

**Comment by robskie** [comment]
@lemire 
I've changed the aforementioned code to this.
```go
	times := make([]int, trials)
	for i := range times {
		start := time.Now()
		for _, p := range packed {
			funpack(p, out)
		}
		times[i] = int(time.Since(start).Nanoseconds())
	}
```
Where `out` is just a pointer to an integer slice. I'm now getting these benchmark results.

```
BenchmarkPack32          	  894 mis
BenchmarkUnPack32        	 2279 mis
BenchmarkDeltaPack32     	 1163 mis
BenchmarkDeltaUnPack32   	 3443 mis
BenchmarkPack64          	  511 mis
BenchmarkUnPack64        	 1596 mis
BenchmarkDeltaPack64     	  577 mis
BenchmarkDeltaUnPack64   	 2265 mis
```

**Comment by lemire** [comment]
@robskie 

Right. So these unpacking numbers are much more interesting.

On a recent machine, you should be able to easily exceed 4000 mis when decoding 32-bit integers. I don't have any direct experience with 64-bit integers but your numbers are what one might expect: somewhere between half the speed of the 32-bit case and the full speed of the 32-bit case. This suggests that on a recent machine, you should be able to get in the  2500 mis to 3000 mis range.

**Comment by robskie** [comment]
Ok. I'll commit the fix later. Thanks again for your help. I'm closing this now.

**Comment by lemire** [comment]
> Unfortunately, I'll be using this to encode integers up to 16 digits long.

Sure. But your deltas can be much smaller.

One critical step is the differential (de-) coding. I have not checked what you do, but it can be painful to differentially decode 64-bit integers. It can be much faster to differentially decode 32-bit deltas, and then upsample.

**Comment by robskie** [comment]
> I have not checked what you do, but it can be painful to differentially decode 64-bit integers.

What I did was similar to the decoding/encoding of 32-bit integers except I used two 64-bit integers per vector instead of four.

> It can be much faster to differentially decode 32-bit deltas, and then upsample.

Ok, I'll try this. But just to make sure I understand you correctly, this will involve extracting four 32-bit deltas then shuffling them to two xmm registers (upsampling) before computing their prefix sum. Is that right?

**Comment by lemire** [comment]
> What I did was similar to the decoding/encoding of 32-bit integers except I used two 64-bit integers per vector instead of four.

This can obviously be much slower.

> Ok, I'll try this. But just to make sure I understand you correctly, this will involve extracting four 32-bit deltas then shuffling them to two xmm registers (upsampling) before computing their prefix sum. Is that right?


Suppose that you have deltas, but they fit nicely in 32 bits, and their sums fit in 32 bits too, even though they correspond to 64 bits. To use an extreme case, suppose that the deltas are less than 1024. It is clearly wasteful to treat them as 64-bit numbers when doing computations.

What I propose you do is to unpack to 32-bit values. Say (delta1, delta2, delta3, delta4). Then you do as in the 32-bit case, computing (delta1, delta1+delta2, delta1+delta2+delta3,delta1+delta2+delta3+delta4). Then you can upsample to 64-bit values and add to the running sum.

The idea is to keep the values as 32-bit values as long as possible, and only generate 64-bit integers are the very end when you have no choice. This way you can make better use of the SIMD instructions. The downside is that you have to upsample, but that's quite cheap.

**Comment by robskie** [comment]
Sorry, I don't quite get it. So I would unpack the deltas into 32-bit values, compute the prefix sums, then convert them to 64-bits?

**Comment by lemire** [comment]
> Sorry, I don't quite get it. So I would unpack the deltas into 32-bit values, compute the prefix sums, then convert them to 64-bits?

Exactly. The insight is that differential coding can be so expensive that speeding it up can accelerate the whole thing.

We do the same thing when decompressing 32-bit integers. See

https://github.com/lemire/SIMDCompressionAndIntersection/blob/master/src/streamvbyte.c#L606-L622

**Comment by robskie** [comment]
I understand that this can increase decoding speeds for 64-bit values that can fit into 32 bits, but how can it speed up decoding 64-bit values that cannot fit into 32 bits but have 32-bit deltas?

**Comment by lemire** [comment]
@robskie 

This can be used to accelerate the prefix sum. All you need is for the local deltas (4 of them) to sum up to a 32-bit value. It does not matter whether the numbers are 64-bit values. All that matters is the deltas and their sums fit in 32 bits.

**Comment by robskie** [comment]
I'm currently using vectorized differential coding from your paper. So instead of having (d1, d1+d2, d1+d2+d3, d1+d2+d3+d4), I'm computing (d1+d5, d2+d6, d3+d7, d4+d8). 

Suppose I have the previous 64-bit sums (p1, p2) and (p3, p4), and I have two sets of 32-bit deltas (d1, d2, d3, d4) and (d5, d6, d7, d8). From what I understand, I have to first add the two deltas and come up with (d1, d2, d3, d4) and (d1+d5, d2+d6, d3+d7, d4+d8). After that, I have to convert them to 64-bit values (d1, d2), (d3, d4), (d1+d5, d2+d6), and (d3+d7, d4+d8). Then add them to the previous 64-bit sums. The final values would be (p1+d1, p2+d2), (p3+d3, p4+d4), (p1+d1+d5, p2+d2+d6), and (p3+d3+d7, p4+d4+d8).

If for example, I know that all the values fit into 32 bits, I can have 32-bit sums (p1, p2, p3, p4) and then just add them to the deltas which results in (p1+d1, p2+d2, p3+d3, p4+d4), (p1+d1+d5, p2+d2+d6, p3+d3+d7, p4+d4+d8) before converting them to 64-bit values.

**Comment by lemire** [comment]
> I'm currently using vectorized differential coding from your paper. So instead of having (d1, d1+d2, d1+d2+d3, d1+d2+d3+d4), I'm computing (d1+d5, d2+d6, d3+d7, d4+d8).

Right. So you are using what we called "D4" at some point. Then the whole discussion takes a different meaning because there is much less to gain from what I described. What we tried to do later was to get nearly the same speed with D1, where you have to compute the whole prefix sum. I assumed you were using D1.

I submit to you that you might want to implement both (D1 and D4) and see which one offers the best trade-off.

Reference:
http://arxiv.org/abs/1401.6399

> Suppose I have the previous 64-bit sums (p1, p2) and (p3, p4), and I have two sets of 32-bit deltas (d1, d2, d3, d4) and (d5, d6, d7, d8). From what I understand, I have to first add the two deltas and come up with (d1, d2, d3, d4) and (d1+d5, d2+d6, d3+d7, d4+d8). After that, I have to convert them to 64-bit values (d1, d2), (d3, d4), (d1+d5, d2+d6), and (d3+d7, d4+d8). Then add them to the previous 64-bit sums. The final values would be (p1+d1, p2+d2), (p3+d3, p4+d4), (p1+d1+d5, p2+d2+d6), and (p3+d3+d7, p4+d4+d8).

Right, and whether doing it this way would be faster or slower than what you are doing already, I do not know.

**Comment by robskie** [comment]
Ok, I'll do some tests to see if I can further increase the decoding speed for 64-bit values.
